### PR TITLE
Disable EditorConfig console output by default

### LINKED ISSUE #62: [Feature request] Disable EditorConfig settings in console output
### 1. Summary

I don't want to see EditorConfig settings in my console output. I don't need it.

### 2. Expected behavior

No EditorConfig settings in my console output.

### 3. Actual behavior

Example of my console output.

<details>
<summary>
<b>Click here to see full output.</b></summary><br>

```json
key evt: control+p
command: show_overlay {"overlay": "goto", "show_files": true}
chr evt: o (0x6f)
chr evt: i (0x69)
chr evt: p (0x70)
key evt: backspace
command: hungry_backspace
key evt: backspace
command: hungry_backspace
chr evt: p (0x70)
chr evt: e (0x65)
chr evt: n (0x6e)

EditorConfig
D:\Поиск Кристиниты\opensearch.xml
{'charset': 'utf-8',
 'end_of_line': 'lf',
 'indent_size': '4',
 'indent_style': 'tab',
 'insert_final_newline': 'true',
 'tab_width': '4',
 'trim_trailing_whitespace': 'true'}

SublimeLinter: xmllint activated: C:\strawberry\c\bin\xmllint.exe 
SublimeLinter: sublimesyntax activated: <builtin> 
FuzzyFilePath cached 791 files in D:/Поиск Кристиниты
key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
Init webFont
_download_font_info
chr evt: e (0x65)
chr evt: x (0x78)
chr evt: a (0x61)
chr evt: l (0x6c)
chr evt: t (0x74)
command: exalt_format_document
command: drag_select {"event": {"button": 1, "x": 267.5, "y": 106.5}}
command: word_highlight_click {"event": {"button": 1, "x": 267.5, "y": 106.5}}
command: drag_select {"event": {"button": 1, "x": 81.5, "y": 62.5}}
command: word_highlight_click {"event": {"button": 1, "x": 81.5, "y": 62.5}}
command: drag_select {"event": {"button": 1, "x": 297.5, "y": 452.5}}
command: word_highlight_click {"event": {"button": 1, "x": 297.5, "y": 455.5}}
15:25:44 INFO  requests.packages.urllib3.connectionpool:805            _new_conn() Starting new HTTPS connection (1): codestats.net
key evt: control+z
command: undo
15:25:46 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "POST /api/my/pulses/ HTTP/1.1" 201 23
key evt: shift+control+z
command: redo
key evt: control+z
command: undo
15:25:56 INFO  requests.packages.urllib3.connectionpool:805            _new_conn() Starting new HTTPS connection (1): codestats.net
15:25:56 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "POST /api/my/pulses/ HTTP/1.1" 201 23
command: drag_select {"event": {"button": 1, "x": 613.5, "y": 479.5}}
command: word_highlight_click {"event": {"button": 1, "x": 613.5, "y": 479.5}}
key evt: control+p
command: show_overlay {"overlay": "goto", "show_files": true}
chr evt: S (0x53)
chr evt: a (0x61)
chr evt: s (0x73)
chr evt: h (0x68)
chr evt: t (0x74)
key evt: backspace
command: hungry_backspace
chr evt: a (0x61)
no such context .repository in Packages/stposh/Support/PowerShell.tmLanguage
no such context .repository in Packages/stposh/Support/PowerShell.tmLanguage
no such context .repository in Packages/stposh/Support/PowerShell.tmLanguage
no such context .repository in Packages/stposh/Support/PowerShell.tmLanguage
chr evt: S (0x53)
key evt: up
command: move {"by": "lines", "forward": false}
key evt: up
command: move {"by": "lines", "forward": false}
key evt: up
command: move {"by": "lines", "forward": false}

EditorConfig
D:\Sublime Text 3\Data\Packages\SashaSublime\SashaSublime.tmTheme
{'charset': 'utf-8',
 'end_of_line': 'lf',
 'indent_size': '4',
 'indent_style': 'tab',
 'insert_final_newline': 'true',
 'tab_width': '4',
 'trim_trailing_whitespace': 'true'}

FuzzyFilePath cached 277 files in D:/Sublime Text 3/Data/Packages/SashaSublime
key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
command: drag_select {"event": {"button": 1, "x": 618.5, "y": 480.5}}
command: word_highlight_click {"event": {"button": 1, "x": 618.5, "y": 478.5}}
key evt: alt+b
command: bang_search_input {}
chr evt: p (0x70)
chr evt: c (0x63)
```
</details><br>

I don't want to see in my console:

```json
EditorConfig
D:\Поиск Кристиниты\opensearch.xml
{'charset': 'utf-8',
 'end_of_line': 'lf',
 'indent_size': '4',
 'indent_style': 'tab',
 'insert_final_newline': 'true',
 'tab_width': '4',
 'trim_trailing_whitespace': 'true'}
```

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install and set EditorConfig → I restart Sublime Text → periodically I get in my console messages with my EditorConfig settings.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

### PR DESCRIPTION
**Pull request by ihodev**
Closes #62

### CODE REVIEW

**Comment by GrayHatter** [comment]
👎 I would never have learned this was the reason all my files were getting broken. The default should be to output when it's clobbering all files.

**Comment by ihodev** [comment]
@GrayHatter `EditorConfig` can break your files? It just sets proper settings per view.

**Comment by GrayHatter** [comment]
UTF-8 + BOM, tabs, and CRLF, are not proper. And if the defaults we're printed, I'd never have figured out it was editorconfig that was breaking my shit.

And if you don't beleve me, save subl3's user prefrences with UTF8 + BOM with CRLF, and tell me this isn't horribly broken.

**Comment by aziz** [comment]
I think this PR should be merged ASAP, even if you want to keep the default "debug" value to True and print by default, it should be possible to turn it off in user settings. 

Printing something (that is not an exception) to console without letting users to turn it off, is just rude and wrong. 
 
Please merge this PR.

**Comment by sindresorhus** [comment]
I'm getting an error message when trying to open the config file from the Package Control menu.

screen shot 2017-06-09 at 16 36 24

It should also have an entry for both default and user settings, like all other plugins.

**Comment by ihodev** [comment]
@sindresorhus I have just checked the code, everything should work fine. I can add separate menu items for `Default` & `User` settings, but what's wrong with the new settings command introduced in [Sublime Text 3116](https://www.sublimetext.com/3dev)?

**Comment by sindresorhus** [comment]
Never mind. It's all good.

**Pull request merged**
