### PR TITLE
Clarify how to use plugin

### PR DESCRIPTION
**Pull request by objarni**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is better documented on the EditorConfig website. If anything is unclear, it should be made more clear there.

As for fixing style issues, that should just happen automatically. User's doesn't need to run any commands.

**Comment by objarni** [comment]
OK, it only happens when I use the Indentation: Reindent spaces command, and when opening files (sometimes).

Is there a way to trigger formatting of the current buffer..?

**Comment by sindresorhus** [comment]
It should be applied on save.

**Comment by objarni** [comment]
It does not happen to me. Fresh ST3 installation, build.gradle file with .editorconfig containing vanilla output of this plugin, only modification [*] to [*.gradle].

I have restarted ST several times, and only way I got formatting to happen is by re-opening build.gradle.

Any hints on how to debug this?

**Pull request closed without merging**
