### PR TITLE
[Fixed] Disable print in Sublime Text console

### PR DESCRIPTION
**Pull request by Kristinita**
### 1. Behavior before pull request

<kbd>Ctrl+P</kbd> → I select a file in command palette → I saw in Sublime Text console, for example,

```json
command: open_file {"file": "D:\\Киролайна\\Саша Величайшая.txt"}

EditorConfig
D:\Киролайна\Саша Величайшая.txt
{'charset': 'utf-8',
 'end_of_line': 'lf',
 'indent_size': '4',
 'indent_style': 'tab',
 'insert_final_newline': 'true',
 'tab_width': '4',
 'trim_trailing_whitespace': 'true'}

```

### 2. Behavior after pull request

```json
command: open_file {"file": "D:\\Киролайна\\Саша Величайшая.txt"}
```

EditorConfig configuration don't print in Sublime Text console.

I tested EditorConfig → other EditorConfig features works for me after pull request.

### 3. Argumentation

1. I never need to see EditorConfig configuration messages in my console. In particular, I do not need to look at my configuration each time as I open my files. I'm not EditorConfig developer.
1. I constantly debug packages in the Sublime Text console, EditorConfig print prevents me from navigating in the console.

### 4. Alternative

I think, you may don't accept this pull request. In that case, please:

1. Enable printing configuration in console in `debug mode`, but not by default.

or

2. Add an option in package settings. For example, if `"print_configuration_in_console"`— `false` → user don't get EditorConfig configuration messages in console.

Thanks.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What is `debug mode`?

**Comment by Kristinita** [comment]
@sindresorhus , why issue is closed? The problem don't fix.

> What is `debug mode`?

`debug mode` — print EditorConfig messages in Sublime Text console, if user have problem with EditorConfig.

Thanks.

**Comment by sindresorhus** [comment]
> why issue is closed?

Because you didn't respond and your changes doesn't actually fix the problem.

> debug mode — mode, when EditorConfig messages print in Sublime Text console, if user have problem with EditorConfig.

We can't really know when the users is having problems with EditorConfig.

---

I'm happy to consider a good pull request that solves the problem, but this is not.

**Comment by Kristinita** [comment]
> I'm happy to consider a good pull request that solves the problem, but this is not.
> and your changes doesn't actually fix the problem.

Why doesn't fix? Arguments? Personally I use EditorConfig Sublime with this patch, and I don't see unexpected EditorConfig messages in Sublime Text console.

Thanks.

**Pull request closed without merging**
